export const browserCoreExamples = [
  "ozzo browser status",
  "ozzo browser start",
  "ozzo browser stop",
  "ozzo browser tabs",
  "ozzo browser open https://example.com",
  "ozzo browser focus abcd1234",
  "ozzo browser close abcd1234",
  "ozzo browser screenshot",
  "ozzo browser screenshot --full-page",
  "ozzo browser screenshot --ref 12",
  "ozzo browser snapshot",
  "ozzo browser snapshot --format aria --limit 200",
  "ozzo browser snapshot --efficient",
  "ozzo browser snapshot --labels",
];

export const browserActionExamples = [
  "ozzo browser navigate https://example.com",
  "ozzo browser resize 1280 720",
  "ozzo browser click 12 --double",
  'ozzo browser type 23 "hello" --submit',
  "ozzo browser press Enter",
  "ozzo browser hover 44",
  "ozzo browser drag 10 11",
  "ozzo browser select 9 OptionA OptionB",
  "ozzo browser upload /tmp/file.pdf",
  'ozzo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ozzo browser dialog --accept",
  'ozzo browser wait --text "Done"',
  "ozzo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ozzo browser console --level error",
  "ozzo browser pdf",
];
